<?php

return array(
	'storage_import' => '进货',

	'permission_admin' => '编辑管理员',
	'permission_admin_comment' => '拥有此项权限的管理员可以将其拥有的权限分配给其他管理员',
	'permission_market' => '管理商品',
	'permission_market_comment' => '',
	'permission_announcement' => '管理公告',
	'permission_announcement_comment' => '',
	'permission_address' => '管理地址',
	'permission_address_comment' => '',
	'permission_system' => '系统设置',
	'permission_system_comment' => '',
	'permission_productunit' => '商品单位',
	'permission_productunit_comment' => '',
	'permission_producttype' => '商品类型',
	'permission_producttype_comment' => '',
	'permission_prepaidreward' => '充值奖励',
	'permission_prepaidreward_comment' => '',
	'permission_salereport' => '销售报表',
	'permission_salereport_comment' => '',
	'permission_balancereport' => '毛利报表',
	'permission_balancereport_comment' => '',
	'permission_bankaccount' => '资金账户',
	'permission_bankaccount_comment' => '',
	'permission_delivery' => '配送设置',
	'permission_delivery_comment' => '',
	'permission_ticket' => '小票设置',
	'permission_ticket_comment' => '',
	'permission_productstorage' => '库存管理',
	'permission_productstorage_comment' => '',
	'permission_payment' => '支付设置',
	'permission_payment_comment' => '',
	'permission_weixin' => '微信设置',
	'permission_weixin_comment' => '',
	'permission_qqconnect' => 'QQ互联设置',
	'permission_qqconnect_comment' => '',
	'permission_orderstat' => '分拣报表',
	'permission_user' => '用户管理',
	'permission_returnedorder' => '退单',
	'permission_userwallet' => '用户钱包',
	'permission_ticketprinter' => '自助印票',
	'permission_order' => '订单管理',
	'permission_order_sort' => '查看待分拣订单',
	'permission_order_sort_w' => '分拣订单',
	'permission_order_deliver' => '查看待配送订单',
	'permission_order_deliver_w' => '配送订单',
	'permission_station' => '配送站管理',

	'product_storage_normal_mode' => '标准',
	'product_storage_booking_mode' => '预售',
);

?>
